version: '3.1'
services :
  db:
    image: postgres:13-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: firewatch
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fw
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
  fw:
    env_file:
      - .env_file
    image: kprod/firewatch:latest
    depends_on:
      - db
#    ports:
#    - "4242:4242"
